# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
#exclude: ^database.py$
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: detect-private-key
    -   id: requirements-txt-fixer

-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/flake8
    rev: "4.0.1"
    hooks:
    -   id: flake8
        args: [--max-line-length=131]
#-   repo: https://github.com/pre-commit/mirrors-mypy
#    rev: 'v0.971'
#    hooks:
#    -   id: mypy
-   repo: https://github.com/pycqa/isort
    rev: "5.10.1"
    hooks:
      - id: isort
        name: isort (python)
        # stages: [push]
#-   repo: https://github.com/pre-commit/mirrors-autopep8
#    rev: 'v1.6.0'  # Use the sha / tag you want to point at
#    hooks:
#        -   id: autopep8
#-   repo: https://github.com/MarcoGorelli/absolufy-imports
#    rev: v0.3.1
#    hooks:
#    -   id: absolufy-imports
-   repo: https://github.com/jendrikseipp/vulture
    rev: 'v2.5'  # or any later Vulture version
    hooks:
        - id: vulture
-   repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
    -   id: codespell
        types_or: [python, rst, markdown]
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.34.0
    hooks:
    -   id: pyupgrade
        args: [--py38-plus]
-   repo: https://github.com/asottile/yesqa
    rev: v1.3.0
    hooks:
    -   id: yesqa
